spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: ${DB_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: none
kafka:
  consumer-enabled: true
  bootstrap-servers: 5.63.154.191:9092,5.63.154.191:9093
  security:
    protocol: PLAINTEXT
    spring.json.value.default.type: com.user.dto.JsonMessage.java
    spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
    spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
  consumer:
    properties:
      spring.json.trusted.packages: "com.user.dto.account.AccountForFriends"
    auto-offset-reset: earliest
    group-id: ${spring.application.name}
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.JsonDeserializer
    max-poll-records: 1
    fetch-max-wait: 36000
    enable-auto-commit: false

  listener:
    poll-timeout: 1800000
    concurrency: 1
    ack-mode: record
  topics:
    friends: friends-topic
