version: "2"
services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka0:
    image: docker.io/bitnami/kafka:3.5
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    expose:
      - "9092"
    hostname: kafka0
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INSIDE://kafka-0:29092,OUTSIDE://localhost:9092,REMOTE://5.63.154.191:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-0:29092,OUTSIDE://localhost:9092,REMOTE://5.63.154.191:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT,REMOTE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2

  kafka1:
    image: docker.io/bitnami/kafka:3.5
    depends_on:
      - zookeeper
    ports:
      - "29093:29092"
      - "9093:9093"
    expose:
      - "9093"
    hostname: kafka1
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INSIDE://kafka1:29092,OUTSIDE://localhost:9092,REMOTE://5.63.154.191:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka1:29092,OUTSIDE://localhost:9092,REMOTE://5.63.154.191:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT,REMOTE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8090:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka0:29092,kafka1:29093
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    links:
      - kafka-0
      - kafka-1
      - zookeeper
